# name = input("please enter ur name:")
# print(f"welcome {name}")
# rollno = input("ur roll no:")
# print(f"ok {rollno}")
m1 = int(input("math marks ="))
m2 = int(input("eng marks="))
m3 = int(input("science marks ="))
m4 = int(input("social marks="))
m5 = int(input("II lang marks="))
m6 = int(input("computers marks="))
print(f"your marks are:",m1,m2,m3,m4,m5,m6)
grade = ((m1+m2+m3+m4+m5+m6)/600)*100
tot= (m1+m2+m3+m4+m5+m6)
print("total marks out of 600:",tot)
print("percentage:", grade)